[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
[[redirects]]
  from = "/AslUzbek/*"
  to = "/AslUzbek/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/AslUzbek/index.html"
  status = 200