[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"  # yoki "20"

[[redirects]]
  from = "/asluzbeklugati/*"
  to = "/asluzbeklugati/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/asluzbeklugati/index.html"
  status = 200